[package]
name = "opencv_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
opencv = {version = "0.63", features = ["highgui", "imgcodecs"]}

[[bin]]
name = "opencv_info"
path = "src/opencv_info.rs"